### ISSUE TITLE
Crash in log.py

### ISSUE THREAD

**Issue by danshearer** [pronovic/hcoop-meetbot#20]
Something in a meeting this morning crashed Hcoop-Meetbot. This is a long-running instance and we've [had a recent meeting](https://lumosql.org/meetings/LumoSQL_Encrypted_Permissions.20220510.0924.html) with no obvious problems. The [.log.html was created](https://lumosql.org/meetings/SSS_and_LumoSQL_Encrypted_Permissions.20220513.0802.log.html), but the #endmeeting command was not recognised, although I could start a new meeting (which I did twice, only one of which is recorded in that raw log.) There is no processed log. The Meetbot log file gives no error message in addition to what was displayed on the console in tmux, and there are no other clues I can see in tmp files or elsewhere in the Meetbot tree.

Hcoop-Meetbot 0.5.0 from PyPI
Limnoria 2021.06.15 running on Python 3.9.2 (default, Feb 28 2021, 17:03:44)

We run the meetbot with:

```
tmux new-session -s supybot -d -n Hcoop-Meetbot /usr/bin/supybot /home/lumosqlorg/hcoop-meetbot/lumosql-meetbot.conf
```

```
ERROR 2022-05-13T11:20:04 Exception id: 0xbfe5c                                            
ERROR 2022-05-13T11:20:25 Uncaught exception in HcoopMeetbot.__call__:                     
Traceback (most recent call last):                                                         
  File "/usr/lib/python3/dist-packages/supybot/log.py", line 368, in m                     
    return f(self, *args, **kwargs)                                                        
  File "/usr/lib/python3/dist-packages/supybot/irclib.py", line 202, in __call__           
    method(irc, msg)                                                                       
  File "/home/lumosqlorg/.local/lib/python3.9/site-packages/HcoopMeetbot/plugin.py", line 70, in doPrivmsg                                                                            
    handler.irc_message(context=context, message=message)                                  
  File "/home/lumosqlorg/.local/lib/python3.9/site-packages/hcoopmeetbotlogic/handler.py", line 51, in irc_message                                                                    
    dispatch(meeting, context, tracked)                                                    
  File "/home/lumosqlorg/.local/lib/python3.9/site-packages/hcoopmeetbotlogic/command.py", line 275, in dispatch                                                                      
    getattr(_DISPATCHER, "%s%s" % (_METHOD_PREFIX, operation))(meeting, context, operation, operand, message)                                                                         
  File "/home/lumosqlorg/.local/lib/python3.9/site-packages/hcoopmeetbotlogic/command.py", line 70, in do_endmeeting                                                                  
    locations = write_meeting(config=config(), meeting=meeting)                            
  File "/home/lumosqlorg/.local/lib/python3.9/site-packages/hcoopmeetbotlogic/writer.py", line 309, in write_meeting                                                                  
    _write_minutes(config, locations, meeting)                                             
  File "/home/lumosqlorg/.local/lib/python3.9/site-packages/hcoopmeetbotlogic/writer.py", line 298, in _write_minutes                                                                 
    "minutes": _MeetingMinutes.for_meeting(config, meeting),                               
  File "/home/lumosqlorg/.local/lib/python3.9/site-packages/hcoopmeetbotlogic/writer.py", line 193, in for_meeting                                                                    
    attendees=_MeetingMinutes._attendees(meeting),                                         
  File "/home/lumosqlorg/.local/lib/python3.9/site-packages/hcoopmeetbotlogic/writer.py", line 214, in _attendees                                                                     
    actions = _MeetingMinutes._attendee_actions(meeting, nick, alias) 
  File "/home/lumosqlorg/.local/lib/python3.9/site-packages/hcoopmeetbotlogic/writer.py", line 222, in _attendee_actions                                                              
    nick_pattern = re.compile(r"\b%s\b" % nick, re.IGNORECASE)                             
  File "/usr/lib/python3.9/re.py", line 252, in compile               
    return _compile(pattern, flags)                                                        
  File "/usr/lib/python3.9/re.py", line 304, in _compile                                   
    p = sre_compile.compile(pattern, flags)                                                
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile        
    p = sre_parse.parse(p, flags)                                                          
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse                               
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)                             
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub                          
    itemsappend(_parse(source, state, verbose, nested + 1,                                 
  File "/usr/lib/python3.9/sre_parse.py", line 549, in _parse         
    raise source.error("unterminated character set",                   
re.error: unterminated character set at position 17                   
```

I connected to this instance using `tmux a`, saw the crash and exited with ^C. After printing the Meetbot shutdown message, tmux crashed, but I think that is probably unrelated to this bug report, and not do with the tmux scrollback buffer in tmux... older tmux is sometimes like that.

I could upgrade to 0.5.1 from PyPI but I won't yet in case we can figure out a reproducer.

Thanks!

**Comment by pronovic** [comment]
The error is coming from [`writer.py:222`](https://github.com/pronovic/hcoop-meetbot/blob/fc4bf468aa5bd427f2301e6a1edaea00e4770270/src/hcoopmeetbotlogic/writer.py#L222), when I'm generating and parsing a regular expression to identify the actions associated with an IRC nickname.  Best guess is that one of the IRC nicknames in your meeting contained some character that has special meaning for regular expressions, maybe `[` or `]`.   The fix is probably just to handle regular `re.error` and return an empty list of actions for that attendee.  I should be able to release a fix in v0.5.2 later today.

**Comment by danshearer** [comment]
I doubt it is `[` or `]` because everyone coming from Matrix has `[m]` and it has always worked so far.

I have not yet managed to reproduce.

(This does remind me that it would be a cool feature to ingest a raw log and regenerate the HTML files.)

**Comment by danshearer** [comment]
> > It's definitely something like that - I reproduced it. Seems like the exception would only happen if the special characters were unmatched, like a single `[` without a matching `]`.
> the solution is to have those participants set an alias in the `#here` statement, like `#here m` if the nick nick is that Matrix `[m]` example you gave.

Ah, we have tried to be consistent with getting everyone to use `#here`.  Ok, will reinforce that until a better fix comes along.

I will upgrade, because we are only a bit of forgetfulness away from having the less obvious problem of unmatched action items. At least the crash was evident.

Thanks Kenneth.

Dan
