### ISSUE TITLE
Inelegant (but seemingly safe) handling of No Space Left on Device

### ISSUE THREAD

**Issue by danshearer** [pronovic/hcoop-meetbot#28]
I typed #endmeeting, and nothing happened. And once more, still nothing happened.

I went to the tmux session and saw the following exceptions saying "No space left". I freed some space, and tried #endmeeting again, and it seems like everything then worked perfectly. Which is great!

```
AttributeError: 'AtomicFile' object has no attribute '_fd'                                                                                                                            
No space left on device, cannot flush log.                                                                                                                                            
ERROR 2022-07-21T22:56:05 Uncaught exception in flusher #2 (<bound method UsersDictionary.flush of <supybot.ircdb.UsersDictionary object at 0x7f674df42180>>):                        
Traceback (most recent call last):                                                                                                                                                    
  File "/usr/lib/python3/dist-packages/supybot/world.py", line 122, in flush                                                                                                          
    f()                                                                                                                                                                               
  File "/usr/lib/python3/dist-packages/supybot/ircdb.py", line 735, in flush                                                                                                          
    fd = utils.file.AtomicFile(self.filename)                                                                                                                                         
  File "/usr/lib/python3/dist-packages/supybot/utils/file.py", line 170, in __init__                                                                                                  
    self._fd = codecs.open(self.tempFilename, mode, encoding=encoding)                                                                                                                
  File "/usr/lib/python3.9/codecs.py", line 905, in open                                                                                                                              
    file = builtins.open(filename, mode, buffering)                                                                                                                                   
OSError: [Errno 28] No space left on device: '/some/place/hcoop-meetbot/data/tmp/users.conf.965150e52561e69464cffcd904cc48f38e1c2619'                                            
No space left on device, cannot flush log.                                                                                                                                            
ERROR 2022-07-21T22:56:05 Exception id: 0x7ef15                                                                                                                                       
Exception ignored in: <function AtomicFile.__del__ at 0x7f674e567820>                                                                                                                 
Traceback (most recent call last):                                                                                                                                                    
  File "/usr/lib/python3/dist-packages/supybot/utils/file.py", line 247, in __del__                                                                                                   
    self.rollback()                                                                                                                                                                   
  File "/usr/lib/python3/dist-packages/supybot/utils/file.py", line 192, in rollback                                                                                                  
    if not self.closed:                                                                                                                                                               
  File "/usr/lib/python3/dist-packages/supybot/utils/file.py", line 183, in closed                                                                                                    
    return self._fd.closed 
```

This is one of a class of similar possible errors in ```file.py``` on the backend. It would be better if they were caught and a message displayed in the channel. 

In fact, there is no out-of-band error communication that I know of, even though this is a communications tool. More broadly, it might be cool if the meetbot knew to log errors to a particular nick, as well as or instead of to the meeting in progress. I have not thought this idea through though.

Thanks again Kenneth!

**Comment by pronovic** [comment]
Hi @danshearer , the exception in that stack trace is coming from [limnoria](https://github.com/progval/Limnoria).  limnoria is the underlying bot framework that hcoop-meetbot uses.   (The exception shows `/usr/lib/python3/dist-packages/supybot`, and limnoria is a Python 3 fork of the older supybot codebase.) Basically, limnoria handles all of the interaction with IRC, and then sends certain events to a handler in hcoop-meetbot, where I can implement the bot-specific logic.  In this case, `AtomicFile` is being used (and the exception handled) at a level far below hcoop-meetbot.  As far as I can tell, it's not something my code has any opportunity to be aware of.  It looks like limnoria itself is failing before it can trigger any events to hcoop-meetbot.  I don't believe I have any control over the error-handling in this type of situation.
